In [412]:
import pandas as pd
import numpy as np

In [413]:
centroids=pd.DataFrame([(1,1.33,2.5),(2,3.33, 4)], columns=['id','x', 'y'])
centroids

   id     x    y
0   1  1.33  2.5
1   2  3.33  4.0

In [414]:
data=pd.DataFrame([(1,1,1.5),
                   (2,1,4.5),
                   (3,2,1.5),
                   (4,2,3.5),
                   (5,3,2.5),
                   (6,5,6)], columns=['id','x', 'y'])
data

   id  x    y
0   1  1  1.5
1   2  1  4.5
2   3  2  1.5
3   4  2  3.5
4   5  3  2.5
5   6  5  6.0

In [419]:
class Kmeans:
    def __init__(self, centroids, data):
        self.initial_centroids=centroids.copy()
        self.initial_centroids.columns += '_c'
        self.initial_centroids['key'] = 1
        self.centroids = self.initial_centroids.copy()
        
        
        self.initial_data = data.copy()
        self.initial_data['k']=-1
        self.initial_data.columns += '_d'
        self.initial_data['key'] = 1
        self.data=self.initial_data.copy()
        
    def assign_clusters(self):

        df_tmp = self.data.merge(self.centroids, how='outer')
        
        #compute euclidan distance
        df_tmp['distance'] = df_tmp.apply(lambda x: np.linalg.norm(
            x[self.data.columns.values.tolist()[1:-2]].values
            -x[self.centroids.columns.values.tolist()[1:-1]].values
        ),axis=1)
        
        df_tmp=df_tmp.sort_values(['id_d','distance']).drop_duplicates(['id_d'],keep='first')
        df_tmp.reset_index(inplace=True)
        df_tmp['k_d']=df_tmp['id_c']
        self.data=df_tmp[self.data.columns.values.tolist()].copy()
        
        
    def calculate_centroids(self):
        cols=self.centroids.columns
        self.centroids=self.data.drop('id_d', axis=1).groupby(['k_d']).agg(['mean'])
        self.centroids.reset_index(inplace=True) 
        self.centroids.columns=cols
        
    def run_iterations(self, iter):
        self.data=self.initial_data.copy()
        self.centroids=self.initial_centroids.copy()
        for i in range(iter):
            print('\n\nITER: '+str(i)+'\n\nPrzed assign: \n', self.data,'\n', self.centroids)
            self.assign_clusters()
            print('\nPo assign: \nDane\n', self.data)
            self.calculate_centroids()
            print('\nPo calc cntroids: \nCentroidy\n', self.centroids)

In [420]:
ex4 = Kmeans(centroids,data)

In [422]:
ex4.run_iterations(5)

ITER: 0

Przed assign:
    id_d  x_d  y_d  k_d  key
0     1    1  1.5   -1    1
1     2    1  4.5   -1    1
2     3    2  1.5   -1    1
3     4    2  3.5   -1    1
4     5    3  2.5   -1    1
5     6    5  6.0   -1    1
    id_c   x_c  y_c  key
0     1  1.33  2.5    1
1     2  3.33  4.0    1

Po assign:
Dane
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    2    1
5     6    5  6.0    2    1

Po calc cntroids:
Centroidy
    id_c  x_c   y_c  key
0     1  1.5  2.75    1
1     2  4.0  4.25    1


ITER: 1

Przed assign:
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    2    1
5     6    5  6.0    2    1
    id_c  x_c   y_c  key
0     1  1.5  2.75    1
1     2  4.0  4.25    1

Po assign:
Dane
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1

Po calc cntroids:
Centroidy
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1


ITER: 2

Przed assign:
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1

Po assign:
Dane
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1

Po calc cntroids:
Centroidy
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1


ITER: 3

Przed assign:
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1

Po assign:
Dane
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1

Po calc cntroids:
Centroidy
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1


ITER: 4

Przed assign:
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1

Po assign:
Dane
    id_d  x_d  y_d  k_d  key
0     1    1  1.5    1    1
1     2    1  4.5    1    1
2     3    2  1.5    1    1
3     4    2  3.5    1    1
4     5    3  2.5    1    1
5     6    5  6.0    2    1

Po calc cntroids:
Centroidy
    id_c  x_c  y_c  key
0     1  1.8  2.7    1
1     2  5.0  6.0    1